kind: Template
apiVersion: v1
metadata:
  name: coolstore-pipeline-template
objects:
  - kind: BuildConfig
    apiVersion: v1 
    metadata:
      name: coolstore-ui-pipeline
    spec:
      source:
        git:
          uri: https://github.com/lohitj/coolstore-microservice
      strategy:
        jenkinsPipelineStrategy  
parameters:
- description: Git source URL for application
  displayName: Git source repository
  name: GIT_SOURCE_URL
  required: false
- displayName: Git template URL for full aplication
  name: GIT_TEMPLATE_URL
  required: false
- description: The name for the application.
  name: APPLICATION_NAME
  required: false
